name: Daily IPTV Update

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 0 点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run update script
      run: python update_script.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add jp.m3u
        git commit -m "Auto-update: $(date +'%Y-%m-%d')"
        git push
